name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Build iOS
      run: |
        cd ios
        flutter build ios --no-codesign

    - name: Build Web
      run: flutter build web
